tools:
    shell:
        allow:
            - find *
            - head *
            - ls *
            - grep *
            - cd *
            - npx tsc *
            - npm run *
            - tail *
            - sleep 3
            - echo *
            - rm *
            - mv *
            - xargs *
            - git add *
            - git commit *
            - git push origin master *
            - git status *
            - "true"
            - git log *
            - git diff *
            - npm ls *
            - npm install *
paths:
    allow:
        - path: /var/folders/8b/5h9d2q1j1fd32dnjq1b5kjbh0000gn/T/**
